CREATE TABLE IF NOT EXISTS projects (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  slug VARCHAR(160) NOT NULL,
  title VARCHAR(180) NOT NULL,
  summary VARCHAR(500) NOT NULL,
  description TEXT NULL,
  cover_src VARCHAR(500) NULL,
  cover_alt VARCHAR(500) NULL,
  status ENUM('draft', 'published', 'archived') NOT NULL DEFAULT 'draft',
  project_type VARCHAR(80) NULL,
  tech_stack JSON NULL,
  repo_url VARCHAR(500) NULL,
  demo_url VARCHAR(500) NULL,
  started_at DATE NULL,
  completed_at DATE NULL,
  featured BOOLEAN NOT NULL DEFAULT FALSE,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY projects_slug_unique (slug),
  KEY projects_status_sort_index (status, featured, sort_order, id),
  KEY projects_featured_index (featured),
  KEY projects_slug_status_index (slug, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
